from dbg import TraceError
from grp import GenerateColor

BASE_THEME_COLOR_RGBA = (0.3, 0.3, 0.3, 1)
BASE_THEME_COLOR = GenerateColor(*BASE_THEME_COLOR_RGBA)

BASE_THEME_EDITBOX_BACKGROUND_COLOR_RGBA = (0.2, 0.2, 0.2, 0.9)
BASE_THEME_EDITBOX_BACKGROUND_COLOR = GenerateColor(*BASE_THEME_EDITBOX_BACKGROUND_COLOR_RGBA)