from dbg import TraceError
from grp import GenerateColor

BASE_THEME_COLOR_RGBA   = (0.3, 0.3, 0.3, 1)
BASE_THEME_COLOR        = GenerateColor(*BASE_THEME_COLOR_RGBA)

BASE_THEME_EDITBOX_BACKGROUND_COLOR_RGBA    = (0.2, 0.2, 0.2, 0.9)
BASE_THEME_EDITBOX_BACKGROUND_COLOR         = GenerateColor(*BASE_THEME_EDITBOX_BACKGROUND_COLOR_RGBA)

SCALE_BORDER_COLOR_RGBA  = (0.5, 0.6, 0.5, 0.13)
BASE_THEME_SCALE_BORDER_COLOR       = GenerateColor(*SCALE_BORDER_COLOR_RGBA)

TEXT_INFO_COLOR_RGBA    = (0.9, 0.9, 0.9, 1)
BASE_THEME_SCALE_INFO_COLOR         = GenerateColor(*TEXT_INFO_COLOR_RGBA)

UI_CLASS_DATA = {}
